apiVersion: v1
kind: Service
metadata:
  name: homework-agent-api
  namespace: homework-agent
spec:
  selector:
    app: homework-agent-api
  ports:
    - name: http
      port: 80
      targetPort: 8000
  type: ClusterIP
